# Generated by Django 5.2.16 on 2026-07-30 11:36

import django.core.validators
import meals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(default=meals.models.new_menu_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=16)),
                ('type', models.CharField(choices=[('kr', 'Korean'), ('premium', 'Premium'), ('takeout', 'Takeout')], max_length=16)),
                ('title_ko', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=4500)),
                ('meal_date', models.DateField()),
                ('meal_time', models.TimeField(default='12:00:00')),
                ('capacity', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('reservation_deadline', models.DateTimeField()),
                ('deposit_amount', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['meal_date', 'meal_time'],
                'indexes': [models.Index(fields=['meal_date', 'meal_time'], name='menu_active_date_idx')],
            },
        ),
    ]
