# Generated by Django 5.2.16 on 2026-07-30 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('options', models.JSONField(default=dict)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='reserved', max_length=16)),
                ('meal_date', models.DateField()),
                ('meal_time', models.TimeField()),
                ('menu_snapshot', models.JSONField(default=dict)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('refunded_amount', models.PositiveIntegerField(default=0)),
                ('enforces_meal_limit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='meals.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['menu', 'status'], name='reservation_menu_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'used']), ('enforces_meal_limit', True)), fields=('user', 'meal_date', 'meal_time'), name='reservation_one_meal_per_user')],
            },
        ),
    ]
