# Generated by Django 5.2.16 on 2026-07-30 11:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('prompt_content', models.TextField()),
                ('temperature', models.DecimalField(decimal_places=2, default='0.20', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service_name', 'version'), name='prompt_template_service_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('service_name',), name='prompt_template_one_active')],
            },
        ),
        migrations.CreateModel(
            name='AiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('stage', models.CharField(choices=[('validation', 'Validation'), ('guardrail', 'Guardrail'), ('main_chat', 'Main chat')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.PositiveIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'stage', '-created_at'], name='ai_log_user_stage_created_idx'), models.Index(fields=['-created_at'], name='ai_log_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'conversation_id', 'created_at'], name='chat_message_conversation_idx')],
            },
        ),
    ]
