/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_menus_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_reservations_me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallet/transactions/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_wallet_transactions_me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Menu: {
            id: string;
            day_of_week: string;
            type: components["schemas"]["MenuTypeEnum"];
            title_ko: string;
            title_en: string;
            price: number;
            /** Format: date */
            meal_date: string;
            /** Format: time */
            meal_time: string;
            capacity: number;
            /** Format: date-time */
            reservation_deadline: string;
            deposit_amount: number;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description * `kr` - kr
         *     * `premium` - premium
         *     * `takeout` - takeout
         * @enum {string}
         */
        MenuTypeEnum: "kr" | "premium" | "takeout";
        PointTransaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            amount: number;
            type: components["schemas"]["PointTransactionTypeEnum"];
            description: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description * `charge` - charge
         *     * `deduct` - deduct
         *     * `refund` - refund
         * @enum {string}
         */
        PointTransactionTypeEnum: "charge" | "deduct" | "refund";
        Profile: {
            /** Format: uuid */
            id: string;
            role: components["schemas"]["RoleEnum"];
            student_id: string;
            name: string;
            current_point: number;
            /** Format: date-time */
            created_at: string;
        };
        Reservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            menu_id: string;
            options: unknown;
            total_price: number;
            status: components["schemas"]["StatusEnum"];
            /** Format: date */
            meal_date: string;
            /** Format: time */
            meal_time: string;
            menu_snapshot: unknown;
            deposit_amount: number;
            refunded_amount: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            cancelled_at: string | null;
            /** Format: date-time */
            used_at: string | null;
        };
        /**
         * @description * `student` - student
         *     * `admin` - admin
         * @enum {string}
         */
        RoleEnum: "student" | "admin";
        /**
         * @description * `reserved` - reserved
         *     * `used` - used
         *     * `cancelled` - cancelled
         *     * `no_show` - no_show
         * @enum {string}
         */
        StatusEnum: "reserved" | "used" | "cancelled" | "no_show";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    v1_menus_list: {
        parameters: {
            query?: {
                active_only?: boolean;
                from_date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"][];
                };
            };
        };
    };
    v1_reservations_me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    v1_wallet_transactions_me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PointTransaction"][];
                };
            };
        };
    };
}
